baseURL = "https://hazyblue.me/"
languageCode = "en-us"
title = "Open To Interpretation"
theme = "vienna"

[params]
        image = "/images/fiske_banner.jpg"
	# Social accounts
	twitter = "hazybluedot"
	github = "hazybluedot"
	author = "Darren"
	bio = ""